spring:
  application:
    name: devicemanagement
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${OIDC_HOST}/realms/myrealm/protocol/openid-connect/certs

server:
  port: 9091