spring:
  application:
    name: devicemanagement
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/certs

server:
  port: ${DEVICEMANAGEMENT_PORT}